I 12-14 19:17:00 replica_managers.py:518] Readiness probe path: /health
I 12-14 19:17:00 replica_managers.py:518] Initial delay seconds: 20
I 12-14 19:17:00 replica_managers.py:518] Post data: None
I 12-14 19:17:00 controller.py:77] Using autoscaler: <class 'sky.serve.autoscalers.SpotRequestRateAutoscaler'>
I 12-14 19:17:00 controller.py:96] Starting autoscaler.
I 12-14 19:17:00 controller.py:180] SkyServe Controller started on http://localhost:20001
I 12-14 19:17:00 controller.py:125] All replica info: []
I 12-14 19:17:00 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:17:00 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 0, Number of ready on-demand instances: 0
I 12-14 19:17:00 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'ACTIVE', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'ACTIVE', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:17:00 spot_policy.py:154] existing_replicas is empty. []
I 12-14 19:17:00 spot_policy.py:161] existing_zones: set()
I 12-14 19:17:00 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'me-central-1b', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ca-central-1d', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'me-south-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'eu-north-1a', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'eu-west-2c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:17:00 autoscalers.py:458] Chosen zone ca-central-1d with DynamicFailoverSpotPlacer()
I 12-14 19:17:00 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'ca-central-1d'})
I 12-14 19:17:00 replica_managers.py:591] Launching replica 1...
I 12-14 19:17:00 replica_managers.py:953] Replicas to probe: 
INFO:     Started server process [16632]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:20001 (Press CTRL+C to quit)
I 12-14 19:17:00 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:17:00 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': False, 'spot_recovery': None})
I 12-14 19:17:00 replica_managers.py:591] Launching replica 2...
I 12-14 19:17:01 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:17:05 httptools_impl.py:496] ::1:42916 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:17:10 replica_managers.py:953] Replicas to probe: 
I 12-14 19:17:20 replica_managers.py:953] Replicas to probe: 
I 12-14 19:17:21 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:17:21 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:17:21 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:17:21 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:17:21 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'ACTIVE', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'ACTIVE', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:17:21 autoscalers.py:525] No scaling needed.
Error in sys.excepthook:

Original exception was:
I 12-14 19:17:25 httptools_impl.py:496] ::1:49078 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:17:30 replica_managers.py:953] Replicas to probe: 
I 12-14 19:17:40 replica_managers.py:775] Launch process for replica 1 finished.
W 12-14 19:17:40 replica_managers.py:781] Launch process for replica 1 exited abnormally with code 1. Terminating...
I 12-14 19:17:40 replica_managers.py:659] Terminating replica 1...
I 12-14 19:17:40 replica_managers.py:678] preempted: False, replica_id: 1
I 12-14 19:17:40 replica_managers.py:953] Replicas to probe: 
I 12-14 19:17:41 controller.py:112] Handle preemption history: ['ca-central-1d']
I 12-14 19:17:41 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}]
I 12-14 19:17:41 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:17:41 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:17:41 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:17:41 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'ACTIVE', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:17:41 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:17:41 spot_policy.py:161] existing_zones: set()
I 12-14 19:17:41 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'me-central-1b', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'me-south-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'eu-north-1a', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'eu-west-2c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:17:41 autoscalers.py:458] Chosen zone eu-west-2c with DynamicFailoverSpotPlacer()
I 12-14 19:17:41 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'eu-west-2c'})
I 12-14 19:17:41 replica_managers.py:591] Launching replica 3...
I 12-14 19:17:41 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:17:45 httptools_impl.py:496] ::1:35012 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:17:50 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:00 replica_managers.py:810] Terminate process for replica 1 finished.
I 12-14 19:18:00 replica_managers.py:849] Termination of replica 1 finished. Replica info is kept since some failure detected.
I 12-14 19:18:01 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:01 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:18:01 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:18:01 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:18:01 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:18:01 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'ACTIVE', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:18:01 autoscalers.py:525] No scaling needed.
Error in sys.excepthook:

Original exception was:
I 12-14 19:18:05 httptools_impl.py:496] ::1:34698 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:18:11 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:20 replica_managers.py:775] Launch process for replica 3 finished.
W 12-14 19:18:20 replica_managers.py:781] Launch process for replica 3 exited abnormally with code 1. Terminating...
I 12-14 19:18:20 replica_managers.py:659] Terminating replica 3...
I 12-14 19:18:20 replica_managers.py:678] preempted: False, replica_id: 3
I 12-14 19:18:21 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:21 controller.py:112] Handle preemption history: ['eu-west-2c']
I 12-14 19:18:21 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:18:21 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:18:21 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:18:21 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:18:21 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:18:21 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:18:21 spot_policy.py:161] existing_zones: set()
I 12-14 19:18:21 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'me-central-1b', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'me-south-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'eu-north-1a', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:18:21 autoscalers.py:458] Chosen zone eu-north-1a with DynamicFailoverSpotPlacer()
I 12-14 19:18:21 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'eu-north-1a'})
I 12-14 19:18:21 replica_managers.py:591] Launching replica 4...
I 12-14 19:18:22 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:18:26 httptools_impl.py:496] ::1:55168 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:18:31 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:41 replica_managers.py:810] Terminate process for replica 3 finished.
I 12-14 19:18:41 replica_managers.py:849] Termination of replica 3 finished. Replica info is kept since some failure detected.
I 12-14 19:18:41 replica_managers.py:953] Replicas to probe: 
I 12-14 19:18:42 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:18:42 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:18:42 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:18:42 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:18:42 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'ACTIVE', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:18:42 autoscalers.py:525] No scaling needed.
Error in sys.excepthook:

Original exception was:
I 12-14 19:18:46 httptools_impl.py:496] ::1:51176 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:18:51 replica_managers.py:953] Replicas to probe: 
I 12-14 19:19:01 replica_managers.py:775] Launch process for replica 4 finished.
W 12-14 19:19:01 replica_managers.py:781] Launch process for replica 4 exited abnormally with code 1. Terminating...
I 12-14 19:19:01 replica_managers.py:659] Terminating replica 4...
I 12-14 19:19:01 replica_managers.py:678] preempted: False, replica_id: 4
I 12-14 19:19:01 replica_managers.py:953] Replicas to probe: 
I 12-14 19:19:02 controller.py:112] Handle preemption history: ['eu-north-1a']
I 12-14 19:19:02 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:19:02 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:19:02 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:19:02 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:19:02 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:19:02 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:19:02 spot_policy.py:161] existing_zones: set()
I 12-14 19:19:02 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'me-central-1b', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'me-south-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:19:02 autoscalers.py:458] Chosen zone me-south-1c with DynamicFailoverSpotPlacer()
I 12-14 19:19:02 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'me-south-1c'})
I 12-14 19:19:02 replica_managers.py:591] Launching replica 5...
I 12-14 19:19:02 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:19:06 httptools_impl.py:496] ::1:34664 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:19:11 replica_managers.py:953] Replicas to probe: 
I 12-14 19:19:21 replica_managers.py:810] Terminate process for replica 4 finished.
I 12-14 19:19:21 replica_managers.py:849] Termination of replica 4 finished. Replica info is kept since some failure detected.
I 12-14 19:19:21 replica_managers.py:953] Replicas to probe: 
Error in sys.excepthook:

Original exception was:
I 12-14 19:19:22 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:19:22 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:19:22 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:19:22 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:19:22 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'ACTIVE', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:19:22 autoscalers.py:525] No scaling needed.
I 12-14 19:19:26 httptools_impl.py:496] ::1:54836 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:19:31 replica_managers.py:953] Replicas to probe: 
I 12-14 19:19:41 replica_managers.py:775] Launch process for replica 5 finished.
W 12-14 19:19:41 replica_managers.py:781] Launch process for replica 5 exited abnormally with code 1. Terminating...
I 12-14 19:19:41 replica_managers.py:659] Terminating replica 5...
I 12-14 19:19:41 replica_managers.py:678] preempted: False, replica_id: 5
I 12-14 19:19:41 replica_managers.py:953] Replicas to probe: 
I 12-14 19:19:42 controller.py:112] Handle preemption history: ['me-south-1c']
I 12-14 19:19:42 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:19:42 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:19:42 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:19:42 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:19:42 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:19:42 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:19:42 spot_policy.py:161] existing_zones: set()
I 12-14 19:19:42 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'me-central-1b', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:19:42 autoscalers.py:458] Chosen zone me-central-1b with DynamicFailoverSpotPlacer()
I 12-14 19:19:42 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'me-central-1b'})
I 12-14 19:19:42 replica_managers.py:591] Launching replica 6...
I 12-14 19:19:43 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:19:46 httptools_impl.py:496] ::1:40786 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:19:51 replica_managers.py:953] Replicas to probe: 
I 12-14 19:20:01 replica_managers.py:810] Terminate process for replica 5 finished.
I 12-14 19:20:01 replica_managers.py:849] Termination of replica 5 finished. Replica info is kept since some failure detected.
I 12-14 19:20:01 replica_managers.py:953] Replicas to probe: 
Error in sys.excepthook:

Original exception was:
I 12-14 19:20:03 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581444}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:20:03 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:20:03 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:20:03 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:20:03 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'ACTIVE', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:20:03 autoscalers.py:525] No scaling needed.
I 12-14 19:20:06 httptools_impl.py:496] ::1:48102 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:20:11 replica_managers.py:953] Replicas to probe: 
I 12-14 19:20:21 replica_managers.py:775] Launch process for replica 6 finished.
W 12-14 19:20:21 replica_managers.py:781] Launch process for replica 6 exited abnormally with code 1. Terminating...
I 12-14 19:20:21 replica_managers.py:659] Terminating replica 6...
I 12-14 19:20:21 replica_managers.py:678] preempted: False, replica_id: 6
I 12-14 19:20:21 replica_managers.py:953] Replicas to probe: 
I 12-14 19:20:23 controller.py:112] Handle preemption history: ['me-central-1b']
I 12-14 19:20:23 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:20:23 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:20:23 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:20:23 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 0
I 12-14 19:20:23 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:20:23 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:20:23 spot_policy.py:161] existing_zones: set()
I 12-14 19:20:23 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'us-east-1f', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:20:23 autoscalers.py:458] Chosen zone us-east-1f with DynamicFailoverSpotPlacer()
I 12-14 19:20:23 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'us-east-1f'})
I 12-14 19:20:23 replica_managers.py:591] Launching replica 7...
I 12-14 19:20:23 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:20:26 httptools_impl.py:496] ::1:51494 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:20:31 replica_managers.py:953] Replicas to probe: 
I 12-14 19:20:41 replica_managers.py:775] Launch process for replica 2 finished.
I 12-14 19:20:41 replica_managers.py:799] replica 2 is on-demand. Skipping adding active or preemption history.
I 12-14 19:20:41 replica_managers.py:810] Terminate process for replica 6 finished.
I 12-14 19:20:41 replica_managers.py:849] Termination of replica 6 finished. Replica info is kept since some failure detected.
I 12-14 19:20:41 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:20:41 replica_managers.py:967] Replica 2 is the first ready replica. Setting uptime to 1702581641.9192896.
Error in sys.excepthook:

Original exception was:
I 12-14 19:20:43 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:20:43 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:20:43 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:20:43 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:20:43 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'ACTIVE', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:20:43 autoscalers.py:525] No scaling needed.
I 12-14 19:20:46 httptools_impl.py:496] ::1:50970 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:20:52 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:21:01 replica_managers.py:775] Launch process for replica 7 finished.
W 12-14 19:21:01 replica_managers.py:781] Launch process for replica 7 exited abnormally with code 1. Terminating...
I 12-14 19:21:01 replica_managers.py:659] Terminating replica 7...
I 12-14 19:21:01 replica_managers.py:678] preempted: False, replica_id: 7
I 12-14 19:21:02 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:21:03 controller.py:112] Handle preemption history: ['us-east-1f']
I 12-14 19:21:03 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:21:03 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:21:03 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:21:03 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:21:03 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:21:03 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:21:03 spot_policy.py:161] existing_zones: set()
I 12-14 19:21:03 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'ap-east-1a', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:21:03 autoscalers.py:458] Chosen zone ap-east-1a with DynamicFailoverSpotPlacer()
I 12-14 19:21:03 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'ap-east-1a'})
I 12-14 19:21:03 replica_managers.py:591] Launching replica 8...
I 12-14 19:21:04 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:21:06 httptools_impl.py:496] ::1:47120 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:21:12 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:21:21 replica_managers.py:810] Terminate process for replica 7 finished.
I 12-14 19:21:21 replica_managers.py:849] Termination of replica 7 finished. Replica info is kept since some failure detected.
I 12-14 19:21:22 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
Error in sys.excepthook:

Original exception was:
I 12-14 19:21:24 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:21:24 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:21:24 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:21:24 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:21:24 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'ACTIVE', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:21:24 autoscalers.py:525] No scaling needed.
I 12-14 19:21:26 httptools_impl.py:496] ::1:60832 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:21:32 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:21:42 replica_managers.py:775] Launch process for replica 8 finished.
W 12-14 19:21:42 replica_managers.py:781] Launch process for replica 8 exited abnormally with code 1. Terminating...
I 12-14 19:21:42 replica_managers.py:659] Terminating replica 8...
I 12-14 19:21:42 replica_managers.py:678] preempted: False, replica_id: 8
I 12-14 19:21:42 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:21:44 controller.py:112] Handle preemption history: ['ap-east-1a']
I 12-14 19:21:44 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:21:44 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:21:44 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:21:44 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:21:44 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:21:44 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:21:44 spot_policy.py:161] existing_zones: set()
I 12-14 19:21:44 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'eu-west-3b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:21:44 autoscalers.py:458] Chosen zone eu-west-3b with DynamicFailoverSpotPlacer()
I 12-14 19:21:44 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'eu-west-3b'})
I 12-14 19:21:44 replica_managers.py:591] Launching replica 9...
I 12-14 19:21:44 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:21:46 httptools_impl.py:496] ::1:50898 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:21:52 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:22:02 replica_managers.py:810] Terminate process for replica 8 finished.
I 12-14 19:22:02 replica_managers.py:849] Termination of replica 8 finished. Replica info is kept since some failure detected.
I 12-14 19:22:03 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
Error in sys.excepthook:

Original exception was:
I 12-14 19:22:04 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 9, 'name': 'sky-service-8b08-9', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:22:04 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:22:04 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:22:04 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:22:04 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'ACTIVE', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:22:04 autoscalers.py:525] No scaling needed.
I 12-14 19:22:06 httptools_impl.py:496] ::1:35986 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:22:13 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:22:22 replica_managers.py:775] Launch process for replica 9 finished.
W 12-14 19:22:22 replica_managers.py:781] Launch process for replica 9 exited abnormally with code 1. Terminating...
I 12-14 19:22:22 replica_managers.py:659] Terminating replica 9...
I 12-14 19:22:22 replica_managers.py:678] preempted: False, replica_id: 9
I 12-14 19:22:23 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:22:24 controller.py:112] Handle preemption history: ['eu-west-3b']
I 12-14 19:22:24 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 9, 'name': 'sky-service-8b08-9', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:22:24 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:22:24 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:22:24 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:22:24 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'PREEMPTED', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:22:24 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:22:24 spot_policy.py:161] existing_zones: set()
I 12-14 19:22:24 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'eu-south-1c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:22:24 autoscalers.py:458] Chosen zone eu-south-1c with DynamicFailoverSpotPlacer()
I 12-14 19:22:24 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'eu-south-1c'})
I 12-14 19:22:24 replica_managers.py:591] Launching replica 10...
I 12-14 19:22:25 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:22:27 httptools_impl.py:496] ::1:34554 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:22:34 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:22:42 replica_managers.py:810] Terminate process for replica 9 finished.
I 12-14 19:22:42 replica_managers.py:849] Termination of replica 9 finished. Replica info is kept since some failure detected.
Error in sys.excepthook:

Original exception was:
I 12-14 19:22:44 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:22:45 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 9, 'name': 'sky-service-8b08-9', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 10, 'name': 'sky-service-8b08-10', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:22:45 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:22:45 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:22:45 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:22:45 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'ACTIVE', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'PREEMPTED', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:22:45 autoscalers.py:525] No scaling needed.
I 12-14 19:22:47 httptools_impl.py:496] ::1:40156 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:22:54 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:23:02 replica_managers.py:775] Launch process for replica 10 finished.
W 12-14 19:23:02 replica_managers.py:781] Launch process for replica 10 exited abnormally with code 1. Terminating...
I 12-14 19:23:02 replica_managers.py:659] Terminating replica 10...
I 12-14 19:23:02 replica_managers.py:678] preempted: False, replica_id: 10
I 12-14 19:23:04 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:23:05 controller.py:112] Handle preemption history: ['eu-south-1c']
I 12-14 19:23:05 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 9, 'name': 'sky-service-8b08-9', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 10, 'name': 'sky-service-8b08-10', 'status': <ReplicaStatus.SHUTTING_DOWN: 'SHUTTING_DOWN'>, 'launched_at': None}]
I 12-14 19:23:05 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:23:05 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:23:05 autoscalers.py:410] Number of alive spot instances: 0, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:23:05 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'PREEMPTED', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'PREEMPTED', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:23:05 spot_policy.py:150] Cannot find zone for replica 2. Skipping adding to existing_zones.
I 12-14 19:23:05 spot_policy.py:161] existing_zones: set()
I 12-14 19:23:05 spot_policy.py:162] unvisited_active_zones: ['ap-southeast-3b', 'us-east-2a', 'us-east-1d', 'ap-southeast-1c', 'eu-south-1b', 'us-west-1a', 'eu-north-1b', 'eu-north-1c', 'ap-south-1c', 'ap-south-1a', 'eu-west-1a', 'ap-southeast-2c', 'ap-southeast-2a', 'ap-northeast-1a', 'eu-west-3c', 'us-west-2c', 'eu-west-3a', 'ap-east-1b', 'me-central-1a', 'us-west-2b', 'ap-northeast-1c', 'us-east-1b', 'ap-northeast-2a', 'ap-northeast-3a', 'ap-northeast-2d', 'us-west-2a', 'ap-northeast-1d', 'eu-west-1c', 'eu-west-1b', 'ap-east-1c', 'ap-northeast-2b', 'us-east-1a', 'ap-southeast-2b', 'af-south-1a', 'eu-west-2b', 'me-central-1c', 'me-south-1a', 'eu-central-1a', 'ap-southeast-1a', 'us-east-2b', 'me-south-1b', 'eu-west-2a', 'ca-central-1b', 'ap-southeast-1b', 'eu-central-1b', 'af-south-1c', 'ap-southeast-3c', 'us-west-2d', 'eu-south-1a', 'ap-northeast-2c', 'eu-central-1c', 'ap-northeast-3c', 'us-east-2c', 'af-south-1b', 'ap-south-1b', 'us-west-1c', 'ca-central-1a', 'ap-southeast-3a', 'ap-northeast-3b', 'us-east-1c']
I 12-14 19:23:05 autoscalers.py:458] Chosen zone us-west-1c with DynamicFailoverSpotPlacer()
I 12-14 19:23:05 controller.py:137] Scaling option received: AutoscalerDecision(AutoscalerDecisionOperator.SCALE_UP, {'use_spot': True, 'spot_recovery': None, 'zone': 'us-west-1c'})
I 12-14 19:23:05 replica_managers.py:591] Launching replica 11...
I 12-14 19:23:05 storage.py:783] Storage type StoreType.S3 already exists.
I 12-14 19:23:07 httptools_impl.py:496] ::1:40002 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:23:14 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:23:22 replica_managers.py:810] Terminate process for replica 10 finished.
I 12-14 19:23:22 replica_managers.py:849] Termination of replica 10 finished. Replica info is kept since some failure detected.
Error in sys.excepthook:

Original exception was:
I 12-14 19:23:24 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
I 12-14 19:23:25 controller.py:125] All replica info: [{'replica_id': 1, 'name': 'sky-service-8b08-1', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 2, 'name': 'sky-service-8b08-2', 'status': <ReplicaStatus.READY: 'READY'>, 'launched_at': 1702581618}, {'replica_id': 3, 'name': 'sky-service-8b08-3', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 4, 'name': 'sky-service-8b08-4', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 5, 'name': 'sky-service-8b08-5', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 6, 'name': 'sky-service-8b08-6', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 7, 'name': 'sky-service-8b08-7', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 8, 'name': 'sky-service-8b08-8', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 9, 'name': 'sky-service-8b08-9', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 10, 'name': 'sky-service-8b08-10', 'status': <ReplicaStatus.FAILED: 'FAILED'>, 'launched_at': None}, {'replica_id': 11, 'name': 'sky-service-8b08-11', 'status': <ReplicaStatus.PROVISIONING: 'PROVISIONING'>, 'launched_at': None}]
I 12-14 19:23:25 autoscalers.py:349] Requests per second: 0.0, Current target number of replicas: 1
I 12-14 19:23:25 autoscalers.py:391] Final target number of replicas: 1 (1 with over-provision), Upscale counter: 0/15, Downscale counter: 0/60
I 12-14 19:23:25 autoscalers.py:410] Number of alive spot instances: 1, Number of ready spot instances: 0, Number of alive on-demand instances: 1, Number of ready on-demand instances: 1
I 12-14 19:23:25 autoscalers.py:421] Current zone to type: {'ap-southeast-3b': 'ACTIVE', 'us-east-2a': 'ACTIVE', 'us-east-1d': 'ACTIVE', 'ap-southeast-1c': 'ACTIVE', 'eu-south-1b': 'ACTIVE', 'us-west-1a': 'ACTIVE', 'eu-north-1b': 'ACTIVE', 'eu-north-1c': 'ACTIVE', 'ap-south-1c': 'ACTIVE', 'ap-south-1a': 'ACTIVE', 'me-central-1b': 'PREEMPTED', 'eu-west-1a': 'ACTIVE', 'ap-southeast-2c': 'ACTIVE', 'ap-southeast-2a': 'ACTIVE', 'ap-northeast-1a': 'ACTIVE', 'eu-west-3c': 'ACTIVE', 'eu-south-1c': 'PREEMPTED', 'us-west-2c': 'ACTIVE', 'eu-west-3a': 'ACTIVE', 'ap-east-1b': 'ACTIVE', 'me-central-1a': 'ACTIVE', 'us-west-2b': 'ACTIVE', 'us-east-1f': 'PREEMPTED', 'ap-northeast-1c': 'ACTIVE', 'us-east-1b': 'ACTIVE', 'ca-central-1d': 'PREEMPTED', 'ap-northeast-2a': 'ACTIVE', 'ap-northeast-3a': 'ACTIVE', 'ap-northeast-2d': 'ACTIVE', 'us-west-2a': 'ACTIVE', 'ap-northeast-1d': 'ACTIVE', 'ap-east-1a': 'PREEMPTED', 'eu-west-1c': 'ACTIVE', 'me-south-1c': 'PREEMPTED', 'eu-west-1b': 'ACTIVE', 'ap-east-1c': 'ACTIVE', 'ap-northeast-2b': 'ACTIVE', 'us-east-1a': 'ACTIVE', 'ap-southeast-2b': 'ACTIVE', 'af-south-1a': 'ACTIVE', 'eu-west-2b': 'ACTIVE', 'me-central-1c': 'ACTIVE', 'me-south-1a': 'ACTIVE', 'eu-central-1a': 'ACTIVE', 'ap-southeast-1a': 'ACTIVE', 'us-east-2b': 'ACTIVE', 'eu-west-3b': 'PREEMPTED', 'eu-north-1a': 'PREEMPTED', 'me-south-1b': 'ACTIVE', 'eu-west-2a': 'ACTIVE', 'ca-central-1b': 'ACTIVE', 'ap-southeast-1b': 'ACTIVE', 'eu-central-1b': 'ACTIVE', 'af-south-1c': 'ACTIVE', 'ap-southeast-3c': 'ACTIVE', 'us-west-2d': 'ACTIVE', 'eu-south-1a': 'ACTIVE', 'ap-northeast-2c': 'ACTIVE', 'eu-central-1c': 'ACTIVE', 'ap-northeast-3c': 'ACTIVE', 'us-east-2c': 'ACTIVE', 'af-south-1b': 'ACTIVE', 'ap-south-1b': 'ACTIVE', 'us-west-1c': 'ACTIVE', 'eu-west-2c': 'PREEMPTED', 'ca-central-1a': 'ACTIVE', 'ap-southeast-3a': 'ACTIVE', 'ap-northeast-3b': 'ACTIVE', 'us-east-1c': 'ACTIVE'}
I 12-14 19:23:25 autoscalers.py:525] No scaling needed.
I 12-14 19:23:27 httptools_impl.py:496] ::1:34918 - "POST /controller/load_balancer_sync HTTP/1.1" 200
I 12-14 19:23:35 replica_managers.py:953] Replicas to probe: replica_2(url=44.204.231.242:8081)
[2mTip: The job will keep running after Ctrl-C.[0m
[2mTip: The job will keep running after Ctrl-C.[0m
